version: '3'

services:
  app:
    image: dunglas/frankenphp:alpine
    container_name: frankenphp
    ports:
      - 80:80
      # - 443:443
      # - 443:443/udp
    volumes:
      - ./:/app/public
      - ./Caddyfile:/etc/caddy/Caddyfile
